apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jwt-demo
  namespace: jwt-demo
spec:
  ingressClassName: traefik
  rules:
    - host: jwt-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jwt-demo
                port:
                  number: 80
