apiVersion: v1
kind: Secret
metadata:
  name: jwt-demo-secret
  namespace: jwt-demo
type: Opaque
stringData:
  # Replace with your own strong value before production use.
  JWT_SECRET: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  JWT_EXPIRATION: "3600000"
